main/urls.py
from django.urls import path
from . import views

app_name= 'main'
urlpatterns = [
    path('',views.main),
]

videoSummarizer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index),
    path('main/',include('main.urls')),
    path('subSummarize',include('subSummarize.urls'))
]
urlpatterns+=staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

class Document(models.Model):
	SUMMARIZE_TYPES = (
		('LR','Lex Rank'),
	)
	videoFile = models.FileField(upload_to='documents/',default='dummy.txt')
	subtitleFile = models.FileField(upload_to='documents/',default='dummy.txt')
	summarizeType = models.CharField(max_length=2,choices=SUMMARIZE_TYPES,default='LR')
	summarizationTime = models.DecimalField(max_digits=4, decimal_places=0, default=60)
	bonusWordsFile = models.FileField(upload_to='documents/',default='dummy.txt')
	stigmaWordsFile = models.FileField(upload_to='documents/',default='dummy.txt')

class Weight(models.Model):
	LR = models.FloatField()
	

main/forms.py
from django import forms
from .models import Document

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('videoFile', 'subtitleFile', 'summarizeType', 'summarizationTime', 'bonusWordsFile', 'stigmaWordsFile' )

    def __init__(self, *args, **kwargs):
    	super(DocumentForm, self).__init__(*args, **kwargs)
    	self.fields['bonusWordsFile'].required = False
    	self.fields['stigmaWordsFile'].required = False

main/views.py
# 1. Make subtitles for videos
# 2. Combine videos in one frame
# 3. Try to do unsupervised algo's

from django.shortcuts import render,redirect
from .models import Document
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from .forms import DocumentForm
from django.conf import settings
from .videoSummarizer import summarizeVideo

from SubtitleGen.subtitle import subtitle_gen
# Create your views here.
def main(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        # print(form)
        videoName=str(request.FILES['videoFile']).replace(' ','_')
        videoURL='.'+str(settings.MEDIA_URL)+'documents/'+videoName
        flag=False
        try:
            if(request.FILES['subtitleFile']):
                print("Subtitles already given")
                subtitleName=str(request.FILES['subtitleFile']).replace(' ','_')
                subtitleURL='.'+str(settings.MEDIA_URL)+'documents/'+subtitleName
        except:
            print("There are no subtitles!We Need to be generated")
            flag=True
        # print("Subt url ::: "+str(subtutleURL));
        # print("Video url ::: "+str(videoURL));
        #if bonusWordsFile and stigmaWordsFile aren't uploaded, default files will be chosen.
        bonusWordsURL='.'+str(settings.MEDIA_URL)+'documents/'+str(request.FILES.get('bonusWordsFile','dummy.txt'))
        stigmaWordsURL='.'+str(settings.MEDIA_URL)+'documents/'+str(request.FILES.get('stigmaWordsFile','dummy.txt'))
        summType = 'LR'
        summarizationTime = 60

        if(flag):
        #generate subtitles parameter1 source and parameter2 file name ("video.") and srt file will be video.srt
            subtitle_gen('.'+str(settings.MEDIA_URL)+'documents/'+videoName,videoName[:-3])
            subtitleURL='.'+str(settings.MEDIA_URL)+'documents/'+videoName[:-3]+'srt'
            # print(videoURL)


            URL=summarizeVideo(videoURL,subtitleURL,summType,summarizationTime,bonusWordsURL,stigmaWordsURL)
            # print(downloadURL)
            videoURL=URL+".mp4"
            subURL=URL+".srt"
            best="none"
            worst="none"
            return render(request,'download.html',{ 'videoURL' : videoURL , 'subURL' : subURL,'best':best,'worst':worst})
    else:
        form = DocumentForm()
        return render(request, 'main.html', {
            'form': form
        })

videoSummarizer/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.conf import settings

def index(request):
    return render(request,'index.html')

main/templates/download.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Video summarizer </title>
    <link rel='stylesheet prefetch' href="{% static "videoSummarizer/css/bulma.css" %}">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <style>
    .form-start {
        margin-top : 30px;
    }
    .submit-button {
        margin-top: 20px;
    }
    .navbar-item{
        padding : 20px;
    }
    .combineSection{
        margin-top : 3%;
        margin-left : 5%;
        margin-right : 5%;
    }
    .diffMethods{
        margin-left : 15%;
        margin-right : 15%;
        color : #2B7CF0;
    }
    </style>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

</head>
<body>
    <!-- Navbar start  -->
    <section class="navbar-menu hero is-dark">
    <div class="navbar-start">
        <div class="navbar-item hero-body">
            <div class="container">
                <h1 class="title">
                  Amadeus

                </h1>
                <h2 class="subtitle">
Video summarizer
                </h2>
            </div>
        </div>
    </div>

    <div class="dwld-url">
    <center>
    {% ifequal best "none" %}
    {% else %}
    <h2> {{best}} have more contribution in the summarized video and {{worst}} have the least contribution amomg all </h2>
    {% endifequal %}
    <h1> Click to download the summarized video </h1>

    <div class="dwldButton">
    <a href=".{{videoURL}}" class="button is-success is-rounded is-large is-focused" download="summarizedVideo.mp4" target="_blank">
    Download video
    </a>
    <a href=".{{subURL}}" class="button is-success is-rounded is-large is-focused" download="summarizedVideo.srt" target="_blank">
      Download subtitle
      </a>
    </div>
    </center>
    </div>

    <div class="foot">
    <footer class="footer">
        <div class="content has-text-centered">
          <p>

          </p>
        </div>
    </footer>
    <div>
</body>
</html>

main/templates/main.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Video summarizer </title>
    <link rel='stylesheet prefetch' href="{% static "videoSummarizer/css/bulma.css" %}">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <style>
    .form-start {
        margin-top : 30px;
    }
    .submit-button {
        margin-top: 20px;
    }
    .navbar-item{
        padding : 20px;
    }
    .combineSection{
        margin-top : 3%;
        margin-left : 5%;
        margin-right : 5%;
    }
    .diffMethods{
        margin-left : 15%;
        margin-right : 15%;
        color : #2B7CF0;
    }
    </style>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

</head>
<body>
    <!-- Navbar start  -->
    <section class="navbar-menu hero is-dark">
    <div class="navbar-start">
        <div class="navbar-item hero-body">
            <div class="container">
                <h1 class="title">
                  Amadeus

                </h1>
                <h2 class="subtitle">
Video summarizer
                </h2>
            </div>
        </div>
    </div>
    <!-- <div class="navbar-end">
        <a class="navbar-item">Summarize from Video URL</a>
    </div> -->
    </section>
    <!-- Navbar end -->


    <div class="navbar-end">
      <!-- <div class="navbar-item">
            <a class="button is-success" href="/subSummarize" >Summarize from VideoURL</a>
      </div> -->
    </div>

  </div>
</nav>

<div class="container is-fluid" >

<form method="post" enctype="multipart/form-data">

                {% csrf_token %}
                {% comment %} {% for field in form.visible_fields %} {% endcomment %}
               <div class="box form-start">
                   <div class="message is-success">
                    <div class="message-header ">
                        <p>Upload video and subtitles</p>
                    </div>
                </div>
<div class="columns">

                <div class="column ">
                </div>
                <div class="column">

                <div class="field">
                <div class="file is-centered is-boxed is-success has-name">
                <label class="file-label">
                {% render_field form.videoFile class="file-input" id="file1" name="resume" %}
                <span class="file-cta">
                <span class="file-icon">
                <i class="fas fa-upload"></i>
                </span>
                <span class="file-label">
                Upload Video File
                </span>
                </span>
                <span class="file-name" id="filename1">
                No file uploaded
                </span>
                </label>
                </div>
                </div>
                </div>
                <div class="column">

                        <div class="field">
                        <div class="file is-centered is-boxed is-success has-name">
                        <label class="file-label">
                        {% render_field form.subtitleFile class="file-input" id="file2" name="resume" %}
                        <span class="file-cta">
                        <span class="file-icon">
                        <i class="fas fa-upload"></i>
                        </span>
                        <span class="file-label">
                        Upload subtitle File
                        </span>
                        </span>
                        <span class="file-name" id="filename2">
                        No file uploaded
                        </span>
                        </label>
                        </div>
                        </div>
                </div>
                <div class="column ">
            </div>
</div>

<div class="columns edmundson-options">
    <div class="column">
            <div class="field">
                    <div class="file is-medium is-success has-name is-fullwidth">
                    <label class="file-label">
                    {% render_field form.bonusWordsFile class="file-input" id="file3" name="resume" %}
                    <span class="file-cta">
                    <span class="file-icon">
                    <i class="fas fa-upload"></i>
                    </span>
                    <span class="file-label">
                    Upload Bonus words File
                    </span>
                    </span>
                    <span class="file-name" id="filename3">
                    No file uploaded
                    </span>
                    </label>
                    </div>
            </div>
        </div>
    <div class="column">
            <div class="field">
                    <div class="file is-medium is-success has-name is-fullwidth">
                    <label class="file-label">
                    {% render_field form.stigmaWordsFile class="file-input" id="file4" name="resume" %}
                    <span class="file-cta">
                    <span class="file-icon">
                    <i class="fas fa-upload"></i>
                    </span>
                    <span class="file-label">
                    Upload Stigma words File
                    </span>
                    </span>
                    <span class="file-name" id="filename4">
                    No file uploaded
                    </span>
                    </label>
                    </div>
            </div>
        </div>
    </div>
</div>
</div>

        <!-- {{ form.as_p }} -->
        <center>
            <button class="button submit-button is-medium is-success" type="submit" name="submitButton" id="submitButton">Submit</button>
        </center>



</form>
</div>
<footer class="footer">
        <div class="content has-text-centered">
          <p>
            <!-- <strong>Video Summarizer </strong> by <a href="https://jgthms.com">Aswanth ,Druval, Aswin, Anupam and Parag</a>. The source code is licensed
            <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. -->
          </p>
        </div>
      </footer>
</body>
<script>
var file1 = document.getElementById("file1");
file1.onchange = function(){
    if(file1.files.length > 0)
    {
      document.getElementById('filename1').innerHTML = file1.files[0].name;
    }
};

var file2 = document.getElementById("file2");
file2.onchange = function(){
    if(file2.files.length > 0)
    {
      document.getElementById('filename2').innerHTML = file2.files[0].name;
    }
};

var file3 = document.getElementById("file3");
file3.onchange = function(){
    if(file3.files.length > 0)
    {
      document.getElementById('filename3').innerHTML = file3.files[0].name;
    }
};

var file4 = document.getElementById("file4");
file4.onchange = function(){
    if(file4.files.length > 0)
    {
      document.getElementById('filename4').innerHTML = file4.files[0].name;
    }
};
</script>
<script>
$(document).ready(function(){
    $(".edmundson-options").hide();
    $("#id_summarizeType").change(function(){
        var value = $("#id_summarizeType").val();
        console.log(value);
        if(value=="ED"){
            $(".edmundson-options").fadeIn();
        }else{
            $(".edmundson-options").fadeOut();
        }
    });
});
$(document).ready(function(){
    $('#combineButton').click(function() {
        checked = $("input[type=checkbox]:checked").length;
        if(checked<2) {
            alert("Select atleast two method");
            return false;
        }
        else{
            return true;
        }
    });
});
$(document).ready(function(){
    $('#submitButton').click(function() {
        index = document.getElementById('filename1').innerHTML.indexOf("No file uploaded");
        if(index != -1){
            alert("Upload a VideoFile!");
            return false;
        }
        return true;
    });
});
</script>
</html>

main/templates/main/download.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css'>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <style>
        .dwld-url{
            margin-top : 10%;
        }
        .foot{
            position:absolute;
            bottom:0;
            width:100%;
            height:100px;
        }
        .dwldButton{
          margin-top : 10px;
        }
    </style>
    <title>Download page </title>
</head>

<body>
    <!-- Navbar start  -->
    <section class="nav hero is-dark" >
            <div class="hero-body">
              <div class="container">
                <h1 class="title">
                  Video summarizer
                </h1>
                <h2 class="subtitle">
                  Summarize your video to any length.
                </h2>
              </div>
            </div>
    </section>
    <!-- Navbar end -->

    <div class="dwld-url">
    <center>
    {% ifequal best "none" %}
    {% else %}
    <h2> {{best}} have more contribution in the summarized video and {{worst}} have the least contribution amomg all </h2>
    {% endifequal %}
    <h1> Click to download the summarized video </h1>

    <div class="dwldButton">
    <a href=".{{videoURL}}" class="button is-success is-rounded is-large is-focused" download="summarizedVideo.mp4" target="_blank">
    Download video
    </a>
    <a href=".{{subURL}}" class="button is-success is-rounded is-large is-focused" download="summarizedVideo.srt" target="_blank">
      Download subtitle
      </a>
    </div>
    </center>
    </div>

    <div class="foot">
    <footer class="footer">
        <div class="content has-text-centered">
          <p>
            <!-- <strong>Video Summarizer </strong> by <a href="https://jgthms.com">Aswanth ,Druval, Aswin, Anupam and Parag</a>. The source code is licensed
            <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. -->
          </p>
        </div>
    </footer>
    <div>
</body>
</html>

main/templates/main/main.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Video summarizer </title>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css'>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <style>
    .form-start {
        margin-top : 30px;
    }
    .submit-button {
        margin-top: 20px;
    }
    .navbar-item{
        padding : 20px;
    }
    .combineSection{
        margin-top : 3%;
        margin-left : 5%;
        margin-right : 5%;
    }
    .diffMethods{
        margin-left : 15%;
        margin-right : 15%;
        color : #2B7CF0;
    }
    </style>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

</head>
<body>
    <!-- Navbar start  -->
{% comment %}     <section class="navbar-menu hero is-dark">
    <div class="navbar-start">
        <div class="navbar-item hero-body">
            <div class="container">
                <h1 class="title">
                  <img src="{% static "main/logo/icon-left-font-monochrome-white.svg" %}>

                </h1>
                <h2 class="subtitle">
                  Summarize your video to any length.
                </h2>
            </div>
        </div>
    </div>
    <!-- <div class="navbar-end">
        <a class="navbar-item">Summarize from Video URL</a>
    </div> -->
    </section> {% endcomment %}
    <!-- Navbar end -->
<nav class="navbar">
  <div class="navbar-menu hero is-success">

    <div class="navbar-start">
        <div class="navbar-item hero-body">
            <div class="container">
                <h1 class="title is-1">
                        <img src="{% static "videoSummarizer/logo/icon-left-font-monochrome-white.svg" %}" >
                </h1>
                <h2 class="subtitle">
                        Summarize your video to any duration.
                </h2>
            </div>
        </div>
    </div>

    <div class="navbar-end">
      <!-- <div class="navbar-item">
            <a class="button is-success" href="/subSummarize" >Summarize from VideoURL</a>
      </div> -->
    </div>

  </div>
</nav>

<div class="container is-fluid" >

<form method="post" enctype="multipart/form-data">

                {% csrf_token %}
                {% comment %} {% for field in form.visible_fields %} {% endcomment %}
               <div class="box form-start">
                   <div class="message is-success">
                    <div class="message-header ">
                        <p>Upload video and subtitles</p>
                    </div>
                </div>
<div class="columns">

                <div class="column ">
                </div>
                <div class="column">

                <div class="field">
                <div class="file is-centered is-boxed is-success has-name">
                <label class="file-label">
                {% render_field form.videoFile class="file-input" id="file1" name="resume" %}
                <span class="file-cta">
                <span class="file-icon">
                <i class="fas fa-upload"></i>
                </span>
                <span class="file-label">
                Upload Video File
                </span>
                </span>
                <span class="file-name" id="filename1">
                No file uploaded
                </span>
                </label>
                </div>
                </div>
                </div>
                <div class="column">

                        <div class="field">
                        <div class="file is-centered is-boxed is-success has-name">
                        <label class="file-label">
                        {% render_field form.subtitleFile class="file-input" id="file2" name="resume" %}
                        <span class="file-cta">
                        <span class="file-icon">
                        <i class="fas fa-upload"></i>
                        </span>
                        <span class="file-label">
                        Upload subtitle File
                        </span>
                        </span>
                        <span class="file-name" id="filename2">
                        No file uploaded
                        </span>
                        </label>
                        </div>
                        </div>
                </div>
                <div class="column ">
            </div>
</div>
<div class="message is-success">
        <div class="message-header ">
                <p>Settings</p>
        </div>
    </div>

<div class="columns edmundson-options">
    <div class="column">
            <div class="field">
                    <div class="file is-medium is-success has-name is-fullwidth">
                    <label class="file-label">
                    {% render_field form.bonusWordsFile class="file-input" id="file3" name="resume" %}
                    <span class="file-cta">
                    <span class="file-icon">
                    <i class="fas fa-upload"></i>
                    </span>
                    <span class="file-label">
                    Upload Bonus words File
                    </span>
                    </span>
                    <span class="file-name" id="filename3">
                    No file uploaded
                    </span>
                    </label>
                    </div>
            </div>
        </div>
    <div class="column">
            <div class="field">
                    <div class="file is-medium is-success has-name is-fullwidth">
                    <label class="file-label">
                    {% render_field form.stigmaWordsFile class="file-input" id="file4" name="resume" %}
                    <span class="file-cta">
                    <span class="file-icon">
                    <i class="fas fa-upload"></i>
                    </span>
                    <span class="file-label">
                    Upload Stigma words File
                    </span>
                    </span>
                    <span class="file-name" id="filename4">
                    No file uploaded
                    </span>
                    </label>
                    </div>
            </div>
        </div>
    </div>
</div>
</div>

        <!-- {{ form.as_p }} -->
        <center>
            <button class="button submit-button is-medium is-success" type="submit" name="submitButton" id="submitButton">Submit</button>
        </center>


</form>
</div>
<footer class="footer">
        <div class="content has-text-centered">
          <p>
            <!-- <strong>Video Summarizer </strong> by <a href="https://jgthms.com">Aswanth ,Druval, Aswin, Anupam and Parag</a>. The source code is licensed
            <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. -->
          </p>
        </div>
      </footer>
</body>
<script>
var file1 = document.getElementById("file1");
file1.onchange = function(){
    if(file1.files.length > 0)
    {
      document.getElementById('filename1').innerHTML = file1.files[0].name;
    }
};

var file2 = document.getElementById("file2");
file2.onchange = function(){
    if(file2.files.length > 0)
    {
      document.getElementById('filename2').innerHTML = file2.files[0].name;
    }
};

var file3 = document.getElementById("file3");
file3.onchange = function(){
    if(file3.files.length > 0)
    {
      document.getElementById('filename3').innerHTML = file3.files[0].name;
    }
};

var file4 = document.getElementById("file4");
file4.onchange = function(){
    if(file4.files.length > 0)
    {
      document.getElementById('filename4').innerHTML = file4.files[0].name;
    }
};
</script>
<script>
$(document).ready(function(){
    $(".edmundson-options").hide();
    $("#id_summarizeType").change(function(){
        var value = $("#id_summarizeType").val();
        console.log(value);
        if(value=="ED"){
            $(".edmundson-options").fadeIn();
        }else{
            $(".edmundson-options").fadeOut();
        }
    });
});
$(document).ready(function(){
    $('#combineButton').click(function() {
        checked = $("input[type=checkbox]:checked").length;
        if(checked<2) {
            alert("Select atleast two method");
            return false;
        }
        else{
            return true;
        }
    });
});
$(document).ready(function(){
    $('#submitButton').click(function() {
        index = document.getElementById('filename1').innerHTML.indexOf("No file uploaded");
        if(index != -1){
            alert("Upload a VideoFile!");
            return false;
        }
        return true;
    });
});
</script>
</html>